### ISSUE TITLE
Configure CD Workflows for Helm Chart

### ISSUE THREAD

**Issue by joaquinrz** [retaildevcrews/ngsa#127]
## Description
- [ ] After an image is successfully built, trigger a deployment workflow that will deploy the ngsa helm chart
- [ ] Helm should rollback the changes if the upgrade is unsuccessful and then fail the deployment
- [ ] Configure the deployment to also be triggered when the helm chart is updated (configmap, etc)

- References #103

**Comment by jofultz** [comment]
We are moving to a GitOps model instead of automation through GitHub Actions. 

Closing as it is now out of scope.
