### ISSUE TITLE
Figure out standard error for NGSA and Loderunner.

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#154]
## Description

What: 
 - Determine which items get logged to stdout versus stderr
 
Why:
- Apps should have consistent output target definitions
- Output targets should facilitate both analytics and debugging activities

When:
- During application lifetime

Where:
 - Deployments

## Tasks
- [x] Document decision and identify required changes

## Acceptance Criteria

 - Design needs to facilitate analytics and debugging #182 

## Constraints
- N/A 

## References:
- References #9

**Comment by dsturgell** [comment]
- If the app crashes, is anything logged to stderr?
- Should the app log anything to stderr instead of stdout?

bartr

- currently, everything is logged to stdout
- we can (and probably should) log warnings / errors to stderror

given the way fluent bit handles json so well, we should consider logging everything to json via stdout. we could then filter that to specific log analytics tables which would make dashboards and alerts super easy.

We should also think about "events". right now, most of our log is "request events".  We could also have events like: start, stop, crash, warning, error, exception. That would give us another field to filter on.

I suggest a spike where we build a console app and quickly try some of these things out end-to-end and then write up the guidance for the "basic" cluster.

We could look at using some type of structured logging instead, but json is simple and ubiquitous, so seems a logical choice for crawl.

**Comment by jofultz** [comment]
After a bit of looking around and reading opinions my thoughts are as follows:
- if it is expected output then stdout
- if it is related to a functional state of the application then stdout 
  - receiving 429, but having retry logic
  - reporting response code on server from a bad request
- if it is related to unexpected application failure then stdout 
  - ran out of retries and can't complete the task
  - request parameters caused an application exception on the server
  - client app received an unexpected response code

This should keep all of the data used for analytics together and separate from logs on hard application failures.
