### ISSUE TITLE
Mechanism to Convey Zone and Region Information in a Common and Consistent Manner

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#174]
**Original Title**
Move zone and region information out of app into fluentbit. https://docs.fluentbit.io/manual/pipeline/filters/modify. 

## Description

The zone and region information is needed for logging in all deployed pods.  Each one has Fluentbit configured and the zone and region information needs to be made available to the Fluentbit configuration so that it may be added to the logs.

This has a few benefits

- further decouples app and logger. only fluentbit has to know where the cluster is located.
- less chance of mismatched zone and region names. ex, capitalization issues between apps, misspellings, etc.
- any app deployed to the cluster can get this location info automagically.

bartr - I like the concept, but not sure how you solve for the issue when l8r is in a different region from the app. The current implementation sends that data back in the trace headers where it gets logged by l8r.

You could modify l8r to have that info about each of the servers, but, then you lose the simplicity of just adding an endpoint to the -s command line.

I wonder if there's a way to extend the k8s config so that it has Zone and Region so we can just grab it from the config?

Potential solutions after customer meeting:
- on cluster creation, use init container in fluentbit daemonset to fetch the node info and save it. the other container in the pod will then have access to the saved info.
- on namespace creation, create a standard configmap with region information. this is automated. apps can choose to use this standard configmap
- on deployment of app, pass region information as variables to helm chart. helm charts will have to follow a standard that exposes these variables.

**Comment by dsturgell** [comment]
ACTION: Work with customer to leverage best practice

**Comment by AAkindele** [comment]
Another consideration. A cluster could span multiple zones in one region. How will this affect final implementation?
