### ISSUE TITLE
Deployments Should Use Multiple Availability Zones

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#208]
Ensure that the resource migration creates the clusters in Regions that support Availability Zones and that the clusters are created using at least 2 availability zones in each region.

docs for AKS: https://docs.microsoft.com/en-us/azure/aks/availability-zones

References: #171
References: #183

**Comment by jofultz** [comment]
Closing as the criteria in this issue have been added to the parent (#183) Acceptance Criteria.
