### ISSUE TITLE
Add Build Checks for TestFiles changes

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#248]
Add build action for ./TestFiles on PR and Push to the [ngsa.yaml](https://github.com/retaildevcrews/ngsa/blob/main/.github/workflows/ngsa.yaml) workflow.

- since the test files are in l8r, I believe we can just use the l8r ci-cd once we convert the ci-cd to use l8r instead of webv

Path needs to be add to:
- [Push paths](https://github.com/retaildevcrews/ngsa/blob/c4f5ae41b1295c7f0ae938ee98645c6ea19fdfc3/.github/workflows/ngsa.yaml#L9)
- [PR paths](https://github.com/retaildevcrews/ngsa/blob/c4f5ae41b1295c7f0ae938ee98645c6ea19fdfc3/.github/workflows/ngsa.yaml#L17)

**Comment by dsturgell** [comment]
References #252
