### ISSUE TITLE
docker runtime

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#256]
Installation links

- https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
- https://kubernetes.io/docs/setup/production-environment/container-runtimes/

## Description

What: 
 - Verify BareMetal doesn't use docker runtime. If so, switch to something else (containerd).
 
Why:
- k8s is deprecating docker as a runtime post 1.20 (currently estimated at late 2021)

When:
- containers are deployed

Where:
 - Kubernetes

## Tasks
- [ ] Verify BareMetal setup does not use Docker to run container
- [ ] Update to another runtime (containerd) if necessary

## Acceptance Criteria

-  Docker is not used for container runtime

## Constraints
- N/A 

## References:
- References #16

**Comment by dsturgell** [comment]
k8s is deprecating docker as a runtime post 1.20 (currently estimated at late 2021)

I think we're using containerd on AKS and bare metal but we need to validate.

I suggest we address post M1

Verify BareMetal doesn't use docker runtime.  If so, switch to something else (containerd).
