### ISSUE TITLE
Fluentbit Container Update

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#259]
## Description

What: 
 - 
 
Why:
- 

When:
- 

Where:
 - 

## Tasks
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Acceptance Criteria

- 

## Constraints
- N/A 

## References:
- References #16

**Comment by jofultz** [comment]
Closing as duplicate of #284.
