### ISSUE TITLE
Test ARC Management and GitOps for Walk Configuration

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#271]
We need to investigate what it takes to enable ARC and if it will help with cluster management and GitOps.

Additionally, we need to:
- provide feedback (e.g., issues, PRs, and CSE Feedback) to PG on 
  - setup and configuration
  - operational characteristics
- Document the pros and cons as part of the spike

- References #11

**Comment by dtzar** [comment]
We've done a bunch of this work already and provided feedback to the PG during our weekly sync and documentation.  Let's sync 😊
