### ISSUE TITLE
NGSA Pods are in ImagePullBackOff state

### ISSUE THREAD

**Issue by kforeverisback** [retaildevcrews/ngsa#292]
NGSA pods are in ImagePullBackOff in all Zones. Issue: Image name is faulty: image: retaildevcrew/ngsa/ngsa:beta-0.0.8-1215-2142-117 (an extra ngsa). Somehow an extra ngsa was inserted.

**Comment by jofultz** [comment]
From Joaquin and Kushal looking at it, we know that there is an extra part "ngsa" in the pull request path.  

Once we figure out what is causing it and how to remediate we should also look at how to enable alerts for GitOps issues.  Maybe we could throw the info into Log Analytics and use alerts there?

**Comment by joaquinrz** [comment]
There is a small bug on the HelmRelease crds when specifying the image repo and name. Straightforward fix.
