### ISSUE TITLE
update helium tests

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/ngsa#294]
The helium tests are broken because of the new year

- [x] update C# and swagger to use 2025 as max year
- [x] update Java code and swagger to use 2025 as max year

**Comment by aflinchb** [comment]
As I understood it, the helium spec, based on the updates to parameter validation, is that 2025 should be hard coded as the max valid year. I created this bug yesterday in the helium repo to track updates: https://github.com/retaildevcrews/helium/issues/632 .  If I misunderstood, we can close or update that bug as well.  Wherever makes the most sense to track it.
