### ISSUE TITLE
use fluentbit debug image

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/ngsa#305]
use fluentbit debug image so that we have shell access in that case that something goes wrong.  

@jofultz to discuss with customer to identify best practice

16 Dec 2020 - sent note to Andrew and Sriram on the topic

aakindele:
We can also try setting the `Log_Level` to `debug`, to see if the logs can provide more information.
https://fluentbit.io/documentation/0.13/configuration/file.html#config_section

Another interesting option is this alpha kubernetes feature. The docs specifically mention distroless containers.
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container

References: #292

**Comment by jofultz** [comment]
For example: https://hub.docker.com/layers/fluent/fluent-bit/1.6-debug/images/sha256-f8bd1d7172fbba1e1c1e640206a99b7735f91fced5e6076b4e7fc493508b7c30?context=explore
