### ISSUE TITLE
Shut down old preprod environments

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#328]
## Description

Remove any unused resources from the old environment. AKS clusters, resource groups, etc.

- [x] Remove OLD Clusters under (east,west,central)
- [x] Remove `preprod-old` folder from `main` in ngsa-cd (https://github.com/retaildevcrews/ngsa-cd/tree/main/releases/preprod-old)
- [x] Remove `old-preprod` branch (https://github.com/retaildevcrews/ngsa-cd/tree/old-preprod)
- [x] Remove old cosmosdb
- ~~Remove old log analytics~~
- [x] Remove unused resource groups

- References https://github.com/retaildevcrews/ngsa/issues/355

**Comment by kforeverisback** [comment]
Finished shutdown and cleanup old-cluster resources.
Old Log Analytics was not deleted since we might want to keep the old logs for archival and test
