### ISSUE TITLE
Debug data from EastUS2 

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#391]
There's no data from EastUS2 in the dashboard currently - need to figure out if something isn't running as expected (maybe a loderunner instance?)

**Comment by kforeverisback** [comment]
One fluentbit instance stopped around 6.15am and the others were working fine.
Both FluentBit and ngsa-cosmos were not restarted.
Ngsa-cosmos logs were working fine (all 200's).

Upon restarting the fluentbit instance (which were running in the node same as ngsa-cosmos) the problem was fixed.

**Comment by kforeverisback** [comment]
These two open-fluentbit issues might be related (fluentbit stops syncing)
https://github.com/fluent/fluent-bit/issues/1065
https://github.com/fluent/fluent-bit/issues/2577

**Comment by dsturgell** [comment]
Reference #400
