### ISSUE TITLE
Add Cosmos metrics to the preview dashboard.  

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#396]
Add Cosmos metrics to the preview dashboard.  This will require configuring the diagnostic setting in our CosmosDB instance to forward the metrics/logs to our log analytics instance (can first test out with the temp LA to see how it behaves).  This way we can compare the RU and 429 data easily with the rest of our charts.

**Comment by gortegaMS** [comment]
All tasks were completed and Cosmos metrics are part of NGSA Dashboard.
