### ISSUE TITLE
update kubeadm reset command

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/ngsa#408]
- you have to remove docker first or kubeadm will use dockerd instead of containerd
- there might be a way to disable dockerd instead - we should check that

```

sudo apt-get remove -y docker-ce docker-ce-cli
sudo shutdown -r now

```

**Comment by AAkindele** [comment]
From these docs it looks like it might be possible to choose the runtime when initializing the cluster. I haven't tried it yet, so not if it works as expected.
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime
