### ISSUE TITLE
Migrate Preview Dashboard to ADX

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#453]

**Comment by gortegaMS** [comment]
New dashboard location 
[ADX - NGS Dashboard](https://dataexplorer.azure.com/dashboards/d67522c2-2c51-4051-a9ae-102c5f0e0762?_startTime=1hours&_endTime=now&_zone=all#00de0ce6-f0e3-4bbf-bd7d-a0a4aea5ab0e)
