### ISSUE TITLE
update k8s-quickstart content

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/ngsa#465]
- AKDC on k8s quick start is out of sync
- per design review will move all of the manual steps content from AKDC to k8s-quickstart

**Comment by atxryan** [comment]
@bartr We had this issue on AKDC at https://github.com/retaildevcrews/akdc/issues/17. We should close or the other.

- update the Dev Cluster content to sync with AKDC
- https://github.com/retaildevcrews/k8s-quickstart/tree/main/02-Dev-Cluster-Setup
