### ISSUE TITLE
Investigate process for setting up a new spoke network in additional region

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#522]
## Description

What: 
 - Identity process for setting a new spoke network with a cluster in a different region (entire package)
 - This includes creating a new Hub network as well for that region.

Why:
- To create a new cluster in a different region per customer requirements

When:
- Initial setup

Where:
 - Azure, Region (East US)

Additional Information:

- These values are from the default aks-secure-baseline walkthrough.
  resource group: rg-enterprise-networking-spokes
- More info about aks-secure-baseline.
  https://github.com/mspnp/aks-secure-baseline
  https://github.com/mspnp/aks-secure-baseline/blob/main/04-networking.md
- The existing work for the spike is here: https://github.com/retaildevcrews/ngsa/tree/main/spikes/aks-secure-baseline
- At a minimum, a new VNet in a different region will be required for the second AKS cluster.
  https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#can-a-vnet-span-regions
- A new Hub in a different region might be needed as well. [Comment from aks-secure-baseline](https://github.com/mspnp/aks-secure-baseline/blob/6b6f04edd9fd7db6b458ecb4a769cb3aa1670c4e/networking/spoke-BU0001A0008.json#L30-L32)

## Tasks
- [ ] Identity process for setting up
- [ ] Document process
- [ ] Design Review

## Acceptance Criteria
- Agreement on process from team

## Constraints
- N/A 

## References:
- References #https://github.com/retaildevcrews/ngsa/issues/473

**Comment by kev-ms** [comment]
References explored to create additional spoke vnet in different region:
- Use existing hub with global Vnet peering:  https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview
  Constraints related to Global Vnet Peering: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#what-are-the-constraints-related-to-global-vnet-peering-and-load-balancers
- hub-and-spoke deployments in different regions: https://aidanfinn.com/?p=21935
- Global transit network Architecture: https://docs.microsoft.com/en-us/azure/virtual-wan/virtual-wan-global-transit-network-architecture

These are some difficulties that team faced while try deploying aks-secure-baseline multiple times
- Lack of abstraction of global setting in the repo made it difficult to customize naming convention
- Multiple users trying to set infrastructure under same subscription ended up in non-unique named resource creations and conflicts
- Some resources are hardcoded in ARM template
- Ambiguity around generating tls certification for pre-prod environment
 
Additional notes: 
1. Step 3 (03-aad.md): TENANTID_AZURERBAC and TENANTID_K8SRBAC are the same tenant id
2. Step 6 (06-gitops.md): User account `bu0001a0008-admin` is created and added to the cluster admin group but it did not have access to the subscription which ended up failing subsequent steps. 
Adding personal user account to the AD security group, created in step 3 (03-aad.md) resolved the issue.
3. Step 4 (04-networking.md): To update your deployment names when creating deployment groups, use the -n option, eg,
az deployment group create -g rg-enterprise-networking-spokes -n <YOUR_DEPLOYMENT_NAME> -f networking/spoke-BU0001A0008.json -p location=eastus2 hubVnetResourceId="${RESOURCEID_VNET_HUB}"
Just be sure to use the updated deployment name in subsequent steps, and check to see if it's hard-coded in any of the ARM templates.

**Comment by kev-ms** [comment]
Team will further explore asks-secure-baseline implementation using terraform #588 
https://github.com/Azure/caf-terraform-landingzones-starter/tree/starter/enterprise_scale/construction_sets/aks/online/aks_secure_baseline
