### ISSUE TITLE
integrate additional ngsa-app cluster with Traefik

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#543]
- integrate ingress with Traefik , cse.ms wildcard cert, and key vault

More info about aks-secure-baseline. https://github.com/mspnp/aks-secure-baseline
The existing work for the spike is here: https://github.com/retaildevcrews/ngsa/tree/main/spikes/aks-secure-baseline

- References https://github.com/retaildevcrews/ngsa/issues/473

**Comment by AAkindele** [comment]
Reduced scope of additional tasks in the deploy spike to only include ngsa-cosmos and fluentbit in another region.
