### ISSUE TITLE
Document PnP deploy feature crew onboarding resources

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#587]
## Description

What: 
 - Document links to resources that the team has found so far around aks-secure-baseline for onboarding
 
Why:
- Improve onboarding experience
- Capture links from different locations in one, easy to find location.

When:
- On-going

Where:
 - Discussions- https://github.com/retaildevcrews/ngsa/discussions/categories/pnp-deploy

## Tasks
- [ ] Document aks-secure-baseline links for onboarding

## Acceptance Criteria
- Enables new dev to quickly upskill on tech
- Enable new dev to quickly onboard to project

## Constraints
- N/A 

## References:
- References

**Comment by gled4er** [comment]
The discussion capturing the links is located here - https://github.com/retaildevcrews/ngsa/discussions/597
