### ISSUE TITLE
TF: Configure Remote Terraform State

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#611]
## Description

- Ensure Terraform state is stored remotely (vs individual computer)
- Resources
  - remote storage: https://www.terraform.io/docs/language/state/remote.html
  - azure backend for terraform: https://www.terraform.io/docs/language/settings/backends/azurerm.html
  - backend config from command line: https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration

- References #588

**Comment by alkofahi** [comment]
For this task, I added a shell script to automate the process of setting up the Terraforms ServicePrincipal and Remote state automatically, the PR can be found here https://github.com/retaildevcrews/caf-terraform-landingzones-starter/pull/2
