### ISSUE TITLE
TF: Customize resources for NGSA

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#614]
## Description
- Customize for NGSA requirements
  - Resource Groups
  - aks cluster
    - VM node size. must have at least 4vCPU. (maybe Standard_DS3_v2)
- naming convention docs. https://github.com/retaildevcrews/ngsa/blob/main/docs/NamingConvention.md
- azure vm sizes. https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-general

- References #588

**Comment by kev-ms** [comment]
We identified different way to tackle resource customization to override default CAF naming convention.
- Assigning prefix in `global_settings.tfvar` to create unique prefix for underlying resources for the implementation. The naming convention would follow `(project-short-form)-(team-name)-(environment)`. This is automatic using CAF module.

- Using locals to override .tfvar assignments to customize resources as needed. This implementation is shelved in spike branch for future reference to implement ci-cd deplyoment.
