### ISSUE TITLE
TF: Evaluate terraform implementation of aks-secure-baseline from CAF

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#618]
## Description
- [x] Review terraform implementation of aks-secure-baseline from CAF
- [x] Implement the default setup
- [x] Create bug issues for items to be updated/resolved
- [x] Review & evaluate with team

Evaluate the terraform implementation for aks-secure-baseline from the Microsoft cloud adoption framework(CAF)
 - The goal is to see how we can reuse existing assets to deploy an environment
 - https://github.com/Azure/caf-terraform-landingzones-starter/tree/starter/enterprise_scale/construction_sets/aks/online/aks_secure_baseline

- References #588 (add user story link)

**Comment by kev-ms** [comment]
Implementing default setup using terraform was successful with minor modification. This changes would be incorporated in forked repo.
1. Update `global_setting.tfvars` to use `eastus2`
2. Admin Azure AD group is not assigned to cluster by default, resulting in failure of initializing 1traffic-ingress-controller
    - Convert `aim-and.ignore` file to tfvar and validate if cluster admins are assigned successfully before creating `SecretProviderClass`
