### ISSUE TITLE
Document Azure Monitor to /spikes

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#628]
Coordinate with AK to enable OMS Agent in pre-prod environment ahead of `aks-secure-baseline` deployment

**Comment by jomalsan** [comment]
With our configuration we want all system level metrics to be collected (default behavior) as well as our application logs and application metrics. The config file (a yaml file representing a configMap) is used to turn on the application log/metric collection and will be created as a part of this story

Sub-Tasks that need to be completed:

- [ ] Research the [config files for Azure Monitor for Containers](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-prometheus-integration)
- [ ] Develop a config file for our deployments in Dev and Pre-Prod. Look at `spikes/oms-log-analytics/3-container-azm-ms-agentconfig.yaml` as a starting point.
- [ ] Enable Azure Monitor for containers in Dev
- [ ] Add the config file to `gitops/deployments/dev`
- [ ] Confirm metric and log flow in dev
- [ ] Enable Azure Monitor for containers in the three pre-prod environments
- [ ] Add the config file to `gitops/deployments/preprod/common`
- [ ] Confirm metric and log flow in preprod
