### ISSUE TITLE
Review: Verify mon-dev environment is deployed correctly

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#646]
Coordinate with PnP-Deploy team to verify environment setup

**Comment by jkeane** [comment]
Related issue #653

**Comment by jomalsan** [comment]
The backend pool for the Application Gateway created gets the URL "bu0001a0008-00.aks-ingress.contoso.com".

Tracking this as we get a service deployed to see if this needs to be changed

**Comment by jomalsan** [comment]
@jkeane showed the solution of changing "bu0001a0008-00.aks-ingress.contoso.com" to "bu0001a0008-00.ngsa-monitoring-dev.com" that will be included in an upcoming PR.

This is the only issue that I saw in the initial configuration and it has been updated
