### ISSUE TITLE
CFG: Verify/Correct Admin permissions on DEV cluster

### ISSUE THREAD

**Issue by jkeane** [retaildevcrews/ngsa#653]
Permissions did not apply correctly during terraform deploy.  Namespaces could not be viewed, etc.  
Find the correct permissions that were missing for the team, correct in portal, then pull back into terraform definition.

**Comment by jomalsan** [comment]
The aks.tfvars has the admin group hard coded to "aks-cluster-re1-admins", but the group that got created with Jim and "NGSA Devs" added to it is named "monitoring-dev-aks-cluster-re1-admins"

https://github.com/retaildevcrews/caf-terraform-landingzones-starter/blob/1b8354fe9518c38930e6d302112832bea73a2003/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/aks.tfvars#L32

**Comment by jomalsan** [comment]
I believe that this PR from Chenmin (https://github.com/retaildevcrews/caf-terraform-landingzones-starter/pull/6) will partially address the issue by adding the creator to new AAD group with access to the cluster. I am following up with her to confirm we saw the same symptoms

**Comment by jomalsan** [comment]
Confirmed with @chenmliu that her fixes are for adding the deployer to the new AAD group that gets permission to the cluster when terraform is deployed. For now we have NGSA Devs configured with access and everyone is able to access it
