### ISSUE TITLE
Security Update for Jumpbox Network Security Group

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#673]
I noticed a security issue on one of the Network Security Group created by CAF terraform

vnet-hub-re1> jumpbox > SSH port 22 is exposed to internet.

The recommendation if a VM is part of this security group:

SSH port 22 is exposed to the Internet. This is only recommended for testing. For production environments, we recommend using a VPN or private connection.

Recommendation
- port 2222
- add secure cyphers

add this to /etc/ssh/sshd_config

ClientAliveInterval 120
Port 2222
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

References: [Issue 5 ](https://github.com/retaildevcrews/caf-terraform-landingzones-starter/issues/15)
References: [PR 8 ] (https://github.com/retaildevcrews/caf-terraform-landingzones-starter/pull/8)

**Comment by gortegaMS** [comment]
We do not have a VM, this was a network security group warning

**Comment by gortegaMS** [comment]
This issue was updated and fixe by PR https://github.com/retaildevcrews/caf-terraform-landingzones-starter/pull/8
