### ISSUE TITLE
DEV: Submit PR to support #607 Traeffic changes to pnp-deploy

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#710]
- [x] Open a PR for traeffic fixes in #607 to https://github.com/retaildevcrews/caf-terraform-landingzones-starter

**Comment by kforeverisback** [comment]
The 02-aks.md file seems to be working with default hard-coded values. Although we feel that, if someone decides to change names and values, it should be generic enough to support custom names and label values. Will talk to AK to make sure, the 02-aks.md readme file has some option to change names/labels
