### ISSUE TITLE
App Service Domain terraform error

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#753]
There was an error while applying the terraform. The portal only showed 3 app service domains at the time of the error.

```bash
Subscription has reached the limit on the number of App Service Domain resources it can create. Please contact support if you want to increase the limit.
```

**Comment by kev-ms** [comment]
https://azure.github.io/AppService/2017/08/08/FAQ-App-Service-Domain-and-Custom-Domains.html

From the article: 
- You may have reached the limit to purchasing domains on your subscription. The current limit is 20.
- If your domain was deleted less than 7 days ago , the domain has not yet started the deletion process.  Hence you can buy the same domain again on Azure portal under the same subscription (make sure to type the exact domain name in search text box).  You will not be charged again for this domain. If the domain was deleted more than 7 days ago , please contact Microsoft Azure support for assistance to restore the domain.
