### ISSUE TITLE
Troubleshoot the error about "unable to mount ssl-csi volume" when deploying Traefik & ASP.net sample application

### ISSUE THREAD

**Issue by gortegaMS** [retaildevcrews/ngsa#754]
When executing step 6 from 02-aks.md we are seeing the following error:

**Comment by gortegaMS** [comment]
What we know so far is that this issue is related to K8s version 1.20.x
It seems to work with K8s version 1.19.9, however we cannot verify since we are blocked by #753

**Comment by kev-ms** [comment]
- The issue only persists with k8s version 1.20+ as described in [change-log](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#urgent-upgrade-notes).
- Found similar issue logged with some other csi drivers
https://github.com/quobyte/quobyte-csi/issues/28

**Comment by kev-ms** [comment]
We will downgrade kubernetes to 1.19.9 to unblock team with this error, further investigate issue in #750
